import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    {
      name: 'production-security-policy',
      apply: 'build',
      transformIndexHtml() {
        return [{ tag: 'meta', attrs: {
          'http-equiv': 'Content-Security-Policy',
          content: "default-src 'self'; script-src 'self' https://apis.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://lh3.googleusercontent.com; font-src 'self'; connect-src 'self' https://*.googleapis.com https://elc-dashboard-d6405.firebaseapp.com; frame-src https://elc-dashboard-d6405.firebaseapp.com https://accounts.google.com; object-src 'none'; base-uri 'none'; form-action 'self'; worker-src 'self'; manifest-src 'self'",
        }, injectTo: 'head-prepend' }];
      },
    },
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Everything here is generated by scripts/generate-icons.mjs into
      // public/, so the manifest can never point at a file that was never made.
      includeAssets: ['favicon.svg', 'favicon-32.png', 'apple-touch-icon.png'],
      manifest: {
        id: '/',
        name: 'UniHelper – Semester 3',
        short_name: 'UniHelper',
        description: 'Timetable, class deadlines, grades and a focus timer.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        display_override: ['standalone', 'minimal-ui'],
        orientation: 'portrait-primary',
        theme_color: '#0b0f14',
        background_color: '#0b0f14',
        categories: ['education', 'productivity'],
        icons: [
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          // A separate file, not the same one tagged "maskable": Android crops
          // a maskable icon to a circle, and the "any" artwork would lose its
          // corners. This one has the glyph pulled into the safe zone.
          { src: 'icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
    })
  ],
})
